[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
linea-testnet = "https://linea-sepolia.infura.io/v3/${INFURA_API_KEY}"
linea-mainnet = "https://linea-mainnet.infura.io/v3/${INFURA_API_KEY}"

[etherscan]
# forge verify-contract --chain 59141 <contract address> src/MyToken.sol:MyToken --watch
linea_testnet = { key = "${LINEASCAN_API_KEY}", chain="59141", url = "https://api-sepolia.lineascan.build/api" }
linea-mainnet = { key = "${LINEASCAN_API_KEY}", url = "https://api.lineascan.build/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
